### ISSUE TITLE
TODO nested injector services

### ISSUE THREAD

**Issue by tractorcow** [tractorcow/silverstripe-framework#10]
``` yaml
Injector:
 One: %$Two
 Two: %$Three
 Three:
   class: Four
```

It crashes on ‘%$Three is not a class'
